### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by zerolab** [wagtail/cookiecutter-wagtail-package#34]
1. for this repos tests
2. for the generated package

Rationale: keeps the management of things in one place. While GHA can be considered a single point of failure, it also removes complexity which we want here. Should a package maintainer go with Circle CI, or something else, that is their prerogative

**Comment by chris48s** [comment]
As well as #45 I'm also working on the 'inner' circle build (for the nightly tests) but I don't have a PR open yet.

**Comment by chris48s** [comment]
https://github.com/wagtail/cookiecutter-wagtail-package/pull/46 now up too
