### ISSUE TITLE
Consistently do or don't delegate linting concerns to pre-commit

### ISSUE THREAD

**Issue by chris48s** [wagtail/cookiecutter-wagtail-package#40]
As of https://github.com/wagtail/cookiecutter-wagtail-package/pull/28 packages generated from this template come with a pre-commit config, but it feels like our approach to this is all over the map. I probably should have identified this more clearly in the review of https://github.com/wagtail/cookiecutter-wagtail-package/pull/28 . We got trigger happy on the merge :(

In the generated package:
- Python-based tooling is completely delegated to pre-commit. Black, flake8, isort etc are specified in `.pre-commit-config.yaml` but they're not specified as dev dependencies in `pyproject.toml`.
- We specify a version of prettier in `.pre-commit-config.yaml` Independently we specify a different version of prettier in `package.json`.
- Also in `package.json` we specify versions of eslint and stylelint + commands for running them, but they aren't run as pre-commit hooks.

In the template repo:
- We `pip install flake8` (which doesn't necessarily check the same version pinned in `.pre-commit-config.yaml` ) in the CI build and check the generated package against it.
- We check the generated package against the versions of stylelint/eslint/prettier specified in `package.json`
- We don't run black/isort/any of the other checks

As it stands, this is not very consistent. We need to fundamentally pick an approach and apply it consistently everywhere. Either dev tools are managed entirely by pre-commit and not installed as dev dependencies or they're both (regardless of ecosystem) and the tools/versions we run against in the template repo CI should be the same what is in the generated package.

**Comment by zerolab** [comment]
#28 had a note re: eslint and other -- I did not tackle it because of the moving targets.

Completely agree we want some consistency. I personally like pre-commit quite a bit (hint: may be biased 😂), and with #34 we can solve the linting part both for the repo, and for the generate package.

**Comment by chris48s** [comment]
I think I _mostly_ agree. Shall we have a quick catch up on this next week? I've not really had the appetite to deal with over xmas.

In the meantime, I've submitted https://github.com/wagtail/cookiecutter-wagtail-package/pull/41 . It is a bit of a "change all the things" :see_no_evil: but I think getting that one in should make it easier for us to make fewer mistakes. Once that one is out of the way, the rest of this pile of issues should be easier for me to work on in parallel as there are less dependencies between them and smaller changesets required.

**Comment by chris48s** [comment]
I'll have a look at this one next
