### ISSUE TITLE
Add Python 3.12 and Wagtail 5.2 to build matrix

### ISSUE THREAD

**Issue by chris48s** [wagtail/cookiecutter-wagtail-package#66]
Refs https://github.com/wagtail/cookiecutter-wagtail-package/pull/59#issuecomment-1747502109

Not quite ready yet, but wagtail 5.2 will be out in the next few weeks

**Comment by chris48s** [comment]
now do-able: https://docs.wagtail.org/en/stable/releases/5.2.html

**Comment by chris48s** [comment]
note - one of the things we need to deal with: https://github.com/wagtail/cookiecutter-wagtail-package/blob/d9ccc7e7204a0e64c562e070af8113f949720c80/%7B%7B%20cookiecutter.__project_name_kebab%20%7D%7D/%7B%7B%20cookiecutter.__project_name_snake%20%7D%7D/test/settings.py#L48

**Comment by zerolab** [comment]
@chris48s that line can be removed as we don't actually do provide anything that would use it
