### ISSUE TITLE
add django 5 to test matrix

### ISSUE THREAD

**Issue by chris48s** [wagtail/cookiecutter-wagtail-package#71]
Add django 5.0 to matrix for compatible combinations of python/wagtail

re: https://docs.djangoproject.com/en/5.0/releases/5.0/#third-party-library-support-for-older-version-of-django should we also start dropping django 3.2 out for new packages, or should we keep it in while in-range wagtail versions still support it?

**Comment by lb-** [comment]
I think for the cookie cutter it makes sense to mostly keep it up to date with **supported** Django versions. I would not see a need for a new package to support older Django versions by default.

Package maintainers may opt into this, but the default should probably be in line with the common case for a brand new package.

**Comment by zerolab** [comment]
In the past, we've tried to align with the Django versions that the supported Wagtail versions did. 

Now that 5.2.2 officially support 5.0, we can progress this. I think we can safely drop anything below 4.2 at this point
